In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.data)  # Access the data (feature values)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
from sklearn.cluster import KMeans
model1 = KMeans(n_clusters=3)
model1.fit(iris.data)
print(model1.labels_)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 1 1 1 1 2 1 1 1 1
 1 1 2 2 1 1 1 1 2 1 2 1 2 1 1 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 2 1
 1 2]


In [ ]:
from sklearn.metrics import silhouette_score
silhouette_avg = silhouette_score(iris.data, model1.labels_)
print("Silhouette Score:", silhouette_avg)

Silhouette Score: 0.551191604619592


In [ ]:
import numpy as np

class MyKMeans:
  def __init__(self, n_clusters=3, max_iter=100, tol=1e-4):
    self.n_clusters = n_clusters
    self.max_iter = max_iter
    self.centroids = None
    self._labels= None
    self.tol = tol


  def _assign_clusters(self, X):
    labels = []
    for point in X:
      min_distance = float('inf')
      closest_cluster = -1
      for i, centroid in enumerate(self.centroids):
        distance = np.sqrt(np.sum((point - centroid) ** 2))
        if distance < min_distance:
          min_distance = distance
          closest_cluster = i
      labels.append(closest_cluster)
    return np.array(labels)


  def fit(self, X):
    X= np.array(X)
    random_indices = np.random.permutation(len(X))[:self.n_clusters]
    self.centroids = X[random_indices]

    for i in range(self.max_iter):
      self._labels = self._assign_clusters(X)
      new_centroids = []

      for j in range(self.n_clusters):
          cluster_points = X[self._labels == j]
          if len(cluster_points) > 0:
              centroid = np.mean(cluster_points, axis=0)
          else:
              centroid = self.centroids[j]
          new_centroids.append(centroid)

      new_centroids = np.array(new_centroids)
      if np.linalg.norm(self.centroids - new_centroids) < self.tol:
        break

      self.centroids = new_centroids


    def predict(self, X):
      return self._assign_clusters(X)

In [ ]:
model2 = MyKMeans(3)
model2.fit(iris.data)
print(model2._labels)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 2 2 2 1 2 2 2 2
 2 2 1 1 2 2 2 2 1 2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 2 2 2 1 2 2 2 1 2 2 2 1 2
 2 1]


In [ ]:
from sklearn.metrics import silhouette_score
s1 = silhouette_score(iris.data, model1.labels_)
s2 = silhouette_score(iris.data, model2._labels)
print("Silhouette Score for sklearn KMeans:", s1)
print("Silhouette Score for MyKMeans:", s2)

Silhouette Score for sklearn KMeans: 0.551191604619592
Silhouette Score for MyKMeans: 0.551191604619592
